task-1-2-1
NikFive/OOP pull request #2
Opened 2022-09-23 04:46 UTC by NikFive

2022-10-03 11:35 UTC, molo4evan commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +    var stackArray //Reminder: change public
См. `//TODO`

2022-10-03 11:35 UTC, molo4evan commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +            result[i] = pop()
Ты имеешь доступ к внутреннему устройству стека, поэлементное выгребание неэффективно

2022-10-03 11:35 UTC, molo4evan commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +    var stackArray //Reminder: change public
И все-таки, почему не private?)

2022-10-03 11:35 UTC, molo4evan commented on task-1-2-1/src/test/kotlin/MyStackTest.kt
> +class MyStackTest {
testPushStack?

2022-10-03 11:35 UTC, molo4evan commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +            push(i)
Аналогично, сделай эффективнее

2022-10-04 06:42 UTC, NikFive commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +    var stackArray //Reminder: change public
Я в тестах проверяю массив, который хранится в стэке. И чтобы мне это сделать без pop, мне нужно иметь к нему доступ

2022-10-04 06:42 UTC, NikFive commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +    var stackArray //Reminder: change public
Иначе я не могу проверить отдельно Push

2022-10-04 06:43 UTC, NikFive commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +    var stackArray //Reminder: change public
Понятно, что пользователю не должен предоставляться доступ к массиву, но чтобы мне протестить push отдельно от pop, мне нужен доступ к самому массиву данных

2022-10-04 06:48 UTC, NikFive commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +    var stackArray //Reminder: change public
Описал проблему ниже

2022-10-08 20:16 UTC, molo4evan commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +    var stackArray //Reminder: change public
Ты все еще можешь хотя бы сделать его internal, чтобы он не был доступен совсем уж повсюду

2022-10-08 20:20 UTC, molo4evan requested changes

2022-10-08 20:20 UTC, molo4evan commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +            stackArray = stackArray.copyOf(len)
А вот это уже лишнее, копировать весь внутренний массив на выгребание 1 элемента - это как-то черезчур

2022-10-09 02:42 UTC, NikFive commented on task-1-2-1/src/main/kotlin/ru/nsu/fit/konstantinov/task_1_2_1/MyStack.kt
> +    var stackArray //Reminder: change public
Сделал через private

2022-10-16 16:13 UTC, molo4evan approved these changes

2022-10-16 16:14 UTC, molo4evan requested changes
Разреши конфликты для fast-forward merge

И засквошь, пожалуйста, коммиты в один, для удобства

2022-10-17 03:43 UTC, merged